### ISSUE TITLE
The discount with minimum percentage is applied if one product is added in two plans having different discount rates.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#27]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Store end --> Membership Plans
Status: new
Version: 1.0.0
Description: The discount with minimum percentage is applied if one product is added in two plans having different discount rates.
![Cart-–-Membership-for-WooCommerce](https://user-images.githubusercontent.com/76723329/109515643-52256980-7acd-11eb-98d7-6ecf1f661972.png)
![Edit-Plan-‹-Membership-for-WooCommerce-—-WordPress (8)](https://user-images.githubusercontent.com/76723329/109515741-6ec1a180-7acd-11eb-9938-a3fe73d29fc3.png)
![Edit-Plan-‹-Membership-for-WooCommerce-—-WordPress (9)](https://user-images.githubusercontent.com/76723329/109515809-86008f00-7acd-11eb-99e3-c210f3c663e5.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.
![Screenshot(8)](https://user-images.githubusercontent.com/76723329/127278925-7eb67e40-9317-493b-a638-ce8738312b49.png)
![Screenshot(9)](https://user-images.githubusercontent.com/76723329/127278955-91d90be3-6e44-42fd-848e-ae8a9b935de6.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
