### ISSUE TITLE
Membership is under review but user is able to purchase product.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#66]
WordPress version: 5.7.2
WooCommerce version: 5.4.1
Area Path: Store
Version: 1.1.0
Description: Membership is under review but the user is able to purchase the product.
![Screenshot(4)](https://user-images.githubusercontent.com/76723329/125295035-7417de00-e342-11eb-9415-a1661d13b9cf.png)
![Screenshot(5)](https://user-images.githubusercontent.com/76723329/125295053-7aa65580-e342-11eb-8892-accc8b10ff1f.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Steps to be followed:
Purchase plan 1 and complete the order.
Purchase plan 2 which contains at least one same product as plan1 and keep the order in pending status.
Observe that same product of Plan1 & Plan2 must be available to purchase as already 1 membership plan is activated.
Purchase plan3 and keep it in pending status then cancel that from members panel.
observe the store where already active membership plan must not be available to purchase after cancelling the plan 3 request.

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed(For simple and variable products).
![Screenshot(1)](https://user-images.githubusercontent.com/76723329/127265177-6ceee2d2-2a4c-47f2-af47-4f389f8f7e55.png)
Membership under review but plan is visible in other membership plan
![Screenshot(2)](https://user-images.githubusercontent.com/76723329/127265205-9a80bd21-ce03-4d9a-9575-a97e92f315cb.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.
![Screenshot(14)](https://user-images.githubusercontent.com/76723329/127627245-6bb58e0e-5b45-4244-b08d-1f49bd850ea4.png)
Also When one plan is active and other is expired the Other membership plans & Under review status are not coming.
![01](https://user-images.githubusercontent.com/76723329/127628084-9de32896-8daa-4f49-a6cc-982f2ef4cc55.png)
![Screenshot(15)](https://user-images.githubusercontent.com/76723329/127628108-1297de78-cc70-4add-a45c-98b09eaacc7d.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
