### ISSUE TITLE
Plugin is not working fine with theme.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#70]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Shop
Version: 1.1.0
Description: Plugin is not working fine with: 
**OceanWP theme-**
Refer: https://drive.google.com/file/d/1T-uEY2mtxufoE8VvbK2HdaILS3_Gsf-3/view?usp=sharing 
**Betheme:**
![Screenshot (26)](https://user-images.githubusercontent.com/76723329/127313843-fe8c0867-aa26-4724-8544-62ebc2da5b3f.png)
![Screenshot (27)](https://user-images.githubusercontent.com/76723329/127313862-80c0ffa7-88c6-4b2b-96b7-fb2740fb6818.png)
![Screenshot (31)](https://user-images.githubusercontent.com/76723329/127329395-85cc395b-2e85-4f36-91c3-58501ff32950.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.
**OceanWP theme-**
Refer: https://drive.google.com/file/d/1T-uEY2mtxufoE8VvbK2HdaILS3_Gsf-3/view?usp=sharing
**Betheme-**
![Screenshot (37)](https://user-images.githubusercontent.com/76723329/127643697-5e741912-d166-4e63-ac66-4566fb7715a7.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
